version: '3.8'

services:
  db:
    image: postgres:17-trixie
    environment:
      POSTGRES_USER: sbomvault
      POSTGRES_PASSWORD: sbomvault
      POSTGRES_DB: sbomvault
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: sbomvault
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
