
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbomvault
    username: sbomvault
    password: sbomvault
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

# https://stackoverflow.com/questions/75372808/vaadin-23-rest-api-and-ui-in-spring-boot-app
vaadin:
  exclude-urls: /api/**

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html

sbomvault:
  cdevents:
    allowTypes:
      - dev.cdevents.artifact.packaged.v1
      - dev.cdevents.artifact.published.v1
      - dev.cdevents.build.finished.v1
      - dev.cdevents.pipeline.run.finished.v1
